vsg-dev/vsgExamples

.gitignore

Excludes more VS incidental build files.

---

Core/vsggroups/vsggroups.cpp
Core/vsgio/vsgio.cpp
Desktop/vsgcompute/vsgcompute.cpp
Desktop/vsgdraw/vsgdraw.cpp
Desktop/vsginput/Text.cpp
Desktop/vsgviewer/vsgviewer.cpp

Updates to use the new ReaderWriter API

Stream readerwriter

---

Desktop/CMakeLists.txt
Desktop/vsgexecutecommands/CMakeLists.txt
Desktop/vsgexecutecommands/vsgexecutecommands.cpp
data/models/raytracing_scene.vsgt
data/models/teapot.vsgt

vsgexecutecommands: 2 windows sharing a commandBuffer via executeCommands
vsgmultiwindow: simple 2 windows with distinct scenegraph

new example for multiple windows test

---

Desktop/vsgintersection/Builder.cpp
Desktop/vsgraytracing/vsgraytracing.cpp
Desktop/vsgrendertotexture/vsgrendertotexture.cpp
Desktop/vsgsubpass/vsgsubpass.cpp

Updates to work with the VSG refactor of the window initialization.  CompileTraversal and RenderPass setup have been streamlined.

Refactor window initialization

---

Desktop/vsgintersection/Builder.cpp
Desktop/vsgviewer/vsgviewer.cpp

Updates to follow Context changes.

Changes for new multisample scheme in VSG

---

Desktop/vsgviewer/vsgviewer.cpp

New option for choosing orthographic projection.

Add --ortho option to vsgviewer

---

CMakeLists.txt
examples/io/vsgio/vsgio.cpp
examples/nodes/vsggroups/vsggroups.cpp
examples/state/vsgtexturearray/CMakeLists.txt
examples/state/vsgtexturearray/vsgtexturearray.cpp
examples/text/vsgtext/CMakeLists.txt
examples/text/vsgtext/vsgtext.cpp
examples/threading/vsgdynamicload/CMakeLists.txt
examples/threading/vsgdynamicload/vsgdynamicload.cpp
examples/traversals/vsgintersection/CMakeLists.txt
examples/traversals/vsgintersection/vsgintersection.cpp
examples/ui/vsgimgui/CMakeLists.txt
examples/ui/vsgimgui/vsgimgui.cpp
examples/viewer/vsgheadless/CMakeLists.txt
examples/viewer/vsgheadless/vsgheadless.cpp
examples/viewer/vsgmultiviews/CMakeLists.txt
examples/viewer/vsgmultiviews/vsgmultiviews.cpp
examples/viewer/vsgoverlay/CMakeLists.txt
examples/viewer/vsgoverlay/vsgoverlay.cpp
examples/viewer/vsgscreenshot/CMakeLists.txt
examples/viewer/vsgscreenshot/vsgscreenshot.cpp
examples/viewer/vsgskybox/CMakeLists.txt
examples/viewer/vsgskybox/vsgskybox.cpp
examples/viewer/vsgviewer/CMakeLists.txt
examples/viewer/vsgviewer/vsgviewer.cpp

Updates to work with the latest VSG, vsgXchange and vsgGIS

Reader writer refactor

---

CMakeLists.txt
examples/viewer/CMakeLists.txt
examples/viewer/vsgdeviceselection/CMakeLists.txt
examples/viewer/vsgdeviceselection/vsgdeviceselection.cpp

Added vsgdeviceselection example.
Added support for generated branches and tags.

Device selection

---

examples/commands/vsgdraw/vsgdraw.cpp
examples/commands/vsgexecutecommands/vsgexecutecommands.cpp
examples/commands/vsginterleaved/vsginterleaved.cpp
examples/core/vsgallocator/vsgallocator.cpp
examples/core/vsgtypes/vsgtypes.cpp
examples/nodes/vsggroups/vsggroups.cpp
examples/raytracing/vsgraytracing/vsgraytracing.cpp
examples/rtx/vsgmeshshader/vsgmeshshader.cpp
examples/state/vsgclip/vsgclip.cpp
examples/state/vsgdynamictexture/vsgdynamictexture.cpp
examples/state/vsgdynamictexture_cs/vsgdynamictexture_cs.cpp
examples/state/vsgtexturearray/vsgtexturearray.cpp
examples/text/vsgtext/vsgtext.cpp
examples/threading/vsgdynamicload/vsgdynamicload.cpp
examples/traversals/vsgintersection/vsgintersection.cpp
examples/utils/vsgbuilder/vsgbuilder.cpp
examples/utils/vsgpoints/vsgpoints.cpp
examples/viewer/vsganaglyphicstereo/vsganaglyphicstereo.cpp
examples/viewer/vsgdeviceselection/vsgdeviceselection.cpp
examples/viewer/vsgheadless/vsgheadless.cpp
examples/viewer/vsgmultigpu/vsgmultigpu.cpp
examples/viewer/vsgortho/vsgortho.cpp
examples/viewer/vsgrendertotexture/vsgrendertotexture.cpp
examples/viewer/vsgscreenshot/vsgscreenshot.cpp
examples/viewer/vsgskybox/vsgskybox.cpp
examples/viewer/vsgsubpass/vsgsubpass.cpp
examples/viewer/vsgviewer/vsgviewer.cpp
examples/vk/vsgcompute/vsgcompute.cpp

Spellcheck Pass

---

examples/io/vsgcluster/Broadcaster.cpp
examples/io/vsgcluster/Broadcaster.h
examples/io/vsgcluster/Receiver.cpp
examples/io/vsgcluster/Receiver.h

Fixed a warning related to redefined macro NOMINMAX with MinGW header 10

---

examples/utils/vsgbuilder/vsgbuilder.cpp

This support is used to compare material setup in osg2vsg (https://github.com/vsg-dev/osg2vsg/issues/63)

Add support to specify diffuse color to vsgbuilder

---

examples/ui/vsgimgui_example/vsgimgui_example.cpp

- The vsgimgui_example has now been extended  to show the ImPlot Demo window.
- Tested on Windows 10 and MacOS Darwin.

vsgimgui_example extended to include ImPlot Demo

---

examples/app/vsgviewer/vsgviewer.cpp

… the --sdi or --shader-debug-info command line options.

Added enabling of the shader debug info during compilation when using the new --sdi or --shader-debug-info command line options.

---

examples/state/CMakeLists.txt
examples/state/vsgdynamicstate/CMakeLists.txt
examples/state/vsgdynamicstate/vsgdynamicstate.cpp

Dear vsg community,
I added this example to demonstrate the use of vsg dynamic state. 
Any feedback is welcome.
Thanks,
Cam

vsg dynamic state demo

---

README.md

replaced the obsolete rtx link with the newer ray tracing link

fixed readme link for raytracing

---

examples/raytracing/vsgraytracing/vsgraytracing.cpp

Updated vsgraytracing example to use data copy mechanism provided by vsg::DataVariance. Changed raw pointer usage to `vsg::ref_ptr<>`. No testing was done.

[UPDATED] vsgraytracing uniform to use dataVariance

---

examples/app/vsgwindows/vsgwindows.cpp

- corrected captions and comment
- fixed typo
- allow to specify the size of the secondary window via command line

Updated the vsgwindows example

---

examples/state/vsgcomputevertex/vsgcomputevertex.cpp
examples/state/vsgdynamictexture_cs/vsgdynamictexture_cs.cpp

Changed vsgcomputevertex and vsgdynamictexture_cs to use a matching queueFamilyIndex for graphics/compute command graphs.
The Vulkan spec 7.7.4 states: "Resources created with a VkSharingMode of VK_SHARING_MODE_EXCLUSIVE must have their ownership explicitly transferred from one queue family to another in order to access their content in a well-defined manner on a queue in a different queue family."
Changes couldn't be properly tested as only one queueFamilyIndex has been observed until now.

[FIXED] compute CommandGraph queueFamily

---

examples/platform/CMakeLists.txt
examples/platform/vsgwin32/CMakeLists.txt
examples/platform/vsgwin32/vsgwin32.cpp

A small example to show how VSG can be integrated into an existing Win32 application and how the events can be processed by the VSG event handler.

Add example for the integration of VSG into an existing Win32 application 

---

examples/app/CMakeLists.txt
examples/app/vsgviewgizmo/CMakeLists.txt
examples/app/vsgviewgizmo/vsgviewgizmo.cpp

This example show a coordinate axis in the upper right corner that tracks the rotation part of the model camera.

Add example of showing a coordinate axis gizmo that tracks the main orientation

---

data/shaders/custom_pbr.frag

Otherwise there are validation errors when running the example it goes with due to the view descriptors changing, and it's unclear which changes are from the custom shader versus which are just it being old.

Update custom_pbr.frag to match standard_pbr.frag

---

data/shaders/custom_pbr.frag
data/shaders/standard_pbr.frag

See https://github.com/vsg-dev/VulkanSceneGraph/issues/1518

Fix emission in PBR shadersets
